repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: cargo-check
        stages: [commit]
      - id: fmt
        stages: [commit]
      - id: clippy
        args: [--all-targets, --all-features]
        stages: [commit]
